# Generated by QSS Toolkit. Import enable_qss_live_preview after QApplication is created.
from pathlib import Path
from PySide6.QtCore import QFileSystemWatcher, QTimer

QSS_PATH = Path("C:/CODE/Git/python-autoreporter/data/styles.qss")
QSS_RELOAD_DELAY_MS = 80


def enable_qss_live_preview(app, qss_path=QSS_PATH, reload_delay_ms=QSS_RELOAD_DELAY_MS):
    qss_path = Path(qss_path)
    watcher = QFileSystemWatcher(app)

    def apply_qss():
        try:
            app.setStyleSheet(qss_path.read_text(encoding="utf-8"))
        except OSError as error:
            print(f"QSS live preview reload failed: {error}")

    def watch_qss():
        directory = str(qss_path.parent)
        if directory not in watcher.directories():
            watcher.addPath(directory)

        file_path = str(qss_path)
        if qss_path.exists() and file_path not in watcher.files():
            watcher.addPath(file_path)

    def reload_qss(_changed_path=None):
        watch_qss()
        QTimer.singleShot(reload_delay_ms, apply_qss)

    watcher.fileChanged.connect(reload_qss)
    watcher.directoryChanged.connect(reload_qss)

    watch_qss()
    apply_qss()
    return watcher